# Generated by Django 5.2.7 on 2026-01-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('customer_full_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15, unique=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator'), ('manager', 'Manager')], default='customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(db_index=True, max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('12:00-13:30', '12:00 PM - 01:30 PM'), ('13:30-15:00', '01:30 PM - 03:00 PM'), ('18:30-20:00', '06:30 PM - 08:00 PM'), ('20:00-21:30', '08:00 PM - 09:30 PM'), ('21:30-23:00', '09:30 PM - 11:00 PM')], max_length=20)),
                ('number_of_guests', models.PositiveIntegerField()),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting for Table'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_app.table')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('booking_date', 'time_slot', 'table')},
            },
        ),
    ]
