# Generated by Django 5.2.7 on 2026-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_reset_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
